# Generated by Django 4.1.7 on 2023-04-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_document_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
