# Generated by Django 4.1.7 on 2023-04-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_action_remove_post_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostAction',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.DeleteModel(
            name='PostStatus',
        ),
    ]
