# Generated by Django 4.1.7 on 2023-04-10 11:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanitarianBottomSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Humanitarian', 'Humanitarian'), ('Peace Education Program', 'Peace Education Program'), ('Peace Education & Knowledge', 'Peace Education & Knowledge')], max_length=50, null=True)),
                ('title', models.CharField(max_length=350, null=True, verbose_name='Title')),
                ('first_desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='First Description')),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Bottom Sections',
            },
        ),
        migrations.CreateModel(
            name='HumanitarianTopSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Humanitarian', 'Humanitarian'), ('Peace Education Program', 'Peace Education Program'), ('Peace Education & Knowledge', 'Peace Education & Knowledge')], max_length=50, null=True)),
                ('title', models.CharField(max_length=350, null=True)),
                ('first_desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='First Description')),
                ('second_desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Second Description')),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Top Section',
            },
        ),
        migrations.DeleteModel(
            name='HumanitarianFirstSection',
        ),
    ]
