# Generated by Django 4.1.7 on 2023-04-10 12:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0002_humanitarianbottomsections_humanitariantopsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeaceEducationProgramSecondSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Peace Education Program Middle Section',
            },
        ),
        migrations.CreateModel(
            name='PeaceEducationProgramTopSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Peace Education Program Top Section',
            },
        ),
        migrations.AlterModelOptions(
            name='humanitarianbottomsections',
            options={'verbose_name_plural': 'Humanitarian Top Section'},
        ),
        migrations.AlterModelOptions(
            name='humanitariantopsection',
            options={'verbose_name_plural': 'Humanitarian Top Section'},
        ),
    ]
