# Generated by Django 4.1.7 on 2023-04-10 14:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0003_peaceeducationprogramsecondsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeaceEducationProgramThiredSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='First Description')),
                ('second_desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Second Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Peace Education Program Middle Section',
            },
        ),
    ]
