# Generated by Django 4.1.7 on 2023-04-10 14:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0005_peaceeducationprogramfourthsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeaceEducationProgramAndEducationFirstSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': '7.Peace Education Program & Education First Section',
            },
        ),
        migrations.AlterModelOptions(
            name='humanitarianbottomsections',
            options={'verbose_name_plural': '2.Humanitarian Bottom Section'},
        ),
        migrations.AlterModelOptions(
            name='humanitariantopsection',
            options={'verbose_name_plural': '1.Humanitarian Top Section'},
        ),
        migrations.AlterModelOptions(
            name='peaceeducationprogramfourthsection',
            options={'verbose_name_plural': '6.Peace Education Program Fourth Section'},
        ),
        migrations.AlterModelOptions(
            name='peaceeducationprogramsecondsection',
            options={'verbose_name_plural': '4.Peace Education Program Second Section'},
        ),
        migrations.AlterModelOptions(
            name='peaceeducationprogramthiredsection',
            options={'verbose_name_plural': '5.Peace Education Program Third Section'},
        ),
        migrations.AlterModelOptions(
            name='peaceeducationprogramtopsection',
            options={'verbose_name_plural': '3.Peace Education Program First Section'},
        ),
    ]
