# Generated by Django 4.1.7 on 2023-04-10 15:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0007_peaceeducationprogramandeducationfirstsection_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeaceEducationProgramAndEducationSecondSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Humanitarian', 'Humanitarian'), ('Peace Education Program', 'Peace Education Program'), ('Peace Education & Knowledge', 'Peace Education & Knowledge')], max_length=50, null=True)),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': '8.Peace Education Program & Education Second Section',
            },
        ),
    ]
