# Generated by Django 4.1.7 on 2023-04-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0008_peaceeducationprogramandeducationsecondsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanitarianbottomsections',
            name='first_desc',
            field=models.TextField(blank=True, null=True, verbose_name='First Description'),
        ),
        migrations.AlterField(
            model_name='humanitariantopsection',
            name='first_desc',
            field=models.TextField(blank=True, null=True, verbose_name='First Description'),
        ),
        migrations.AlterField(
            model_name='humanitariantopsection',
            name='second_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Second Description'),
        ),
        migrations.AlterField(
            model_name='peaceeducationprogramandeducationfirstsection',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='peaceeducationprogramandeducationsecondsection',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='peaceeducationprogramfourthsection',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='peaceeducationprogramsecondsection',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='peaceeducationprogramthiredsection',
            name='first_desc',
            field=models.TextField(blank=True, null=True, verbose_name='First Description'),
        ),
        migrations.AlterField(
            model_name='peaceeducationprogramthiredsection',
            name='second_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Second Description'),
        ),
        migrations.AlterField(
            model_name='peaceeducationprogramtopsection',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
