# Generated by Django 4.1.7 on 2023-03-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.CharField(default='host', max_length=255),
            preserve_default=False,
        ),
    ]
