# Generated by Django 4.1.7 on 2023-04-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventregisteruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
