# Generated by Django 4.1.7 on 2023-04-08 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0012_alter_event_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisteruser',
            name='address',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='eventregisteruser',
            name='city',
            field=models.CharField(max_length=250, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='eventregisteruser',
            name='country',
            field=models.CharField(max_length=250, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='eventregisteruser',
            name='email',
            field=models.CharField(max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='eventregisteruser',
            name='first_name',
            field=models.CharField(max_length=250, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='eventregisteruser',
            name='last_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='eventregisteruser',
            name='phone_number',
            field=models.CharField(max_length=250, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='eventregisteruser',
            name='pin_code',
            field=models.CharField(max_length=250, null=True, verbose_name='Pin Code'),
        ),
        migrations.AddField(
            model_name='eventregisteruser',
            name='smart_card_number',
            field=models.CharField(max_length=250, null=True, verbose_name='Smart Card Number'),
        ),
        migrations.AddField(
            model_name='eventregisteruser',
            name='state',
            field=models.CharField(max_length=250, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='eventregisteruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
