# Generated by Django 4.1.7 on 2023-04-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisteruser',
            name='order_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregisteruser',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
