# Generated by Django 4.1.7 on 2023-04-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_eventregisteruser_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregisteruser',
            name='is_pay',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
