# Generated by Django 4.1.7 on 2023-04-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_eventregisteruser_is_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisteruser',
            name='amount',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
