# Generated by Django 4.1.7 on 2023-04-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_is_event_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_event_complete',
            field=models.BooleanField(default=False, null=True, verbose_name='Is event completed?'),
        ),
    ]
