# Generated by Django 4.1.7 on 2023-04-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_event_is_event_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
    ]
