# Generated by Django 4.1.7 on 2023-04-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_event_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisteruser',
            name='card_details',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
