# Generated by Django 4.1.7 on 2023-04-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisteruser',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
