# Generated by Django 4.1.7 on 2023-04-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregisteruser',
            name='event',
        ),
    ]
