# Generated by Django 4.1.7 on 2023-04-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_eventregisteruser_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
