# Generated by Django 4.1.7 on 2023-04-12 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0027_alter_event_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Paid Event'},
        ),
        migrations.CreateModel(
            name='FreeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, null=True, verbose_name='Event Name')),
                ('host_name', models.CharField(max_length=255, null=True, verbose_name='Host Name')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Event Image')),
                ('location', models.CharField(max_length=255, null=True)),
                ('capacity', models.PositiveIntegerField(null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start', models.DateTimeField(null=True, verbose_name='Event Start Time')),
                ('is_event_complete', models.BooleanField(default=False, null=True, verbose_name='Is event completed?')),
                ('user', models.ManyToManyField(blank=True, related_name='free_event_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Free Event',
            },
        ),
    ]
