# Generated by Django 4.1.7 on 2023-04-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_event_options_freeevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_price',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Event Price'),
        ),
    ]
