# Generated by Django 4.1.7 on 2023-04-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_event_event_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeEvent',
        ),
    ]
