# Generated by Django 4.1.7 on 2023-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_delete_freeevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_price',
            field=models.CharField(blank=True, default='Free', max_length=250, null=True, verbose_name='Event Price'),
        ),
    ]
