# Generated by Django 4.1.7 on 2023-04-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_alter_event_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisteruser',
            name='token',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
