# Generated by Django 4.1.7 on 2023-04-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_eventregisteruser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregisteruser',
            name='token',
        ),
    ]
