# Generated by Django 4.1.7 on 2023-04-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_remove_eventregisteruser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisteruser',
            name='booking_id',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
