# Generated by Django 4.1.7 on 2023-04-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_eventregisteruser_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisteruser',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
