# Generated by Django 4.1.7 on 2023-03-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('qualification', models.CharField(max_length=30)),
                ('oppotunities', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('cv', models.FileField(upload_to='')),
            ],
        ),
    ]
