# Generated by Django 4.1.7 on 2023-04-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, null=True)),
                ('news_document', models.FileField(null=True, upload_to='', verbose_name='news document')),
            ],
        ),
    ]
