# Generated by Django 4.1.7 on 2023-04-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Newses'},
        ),
    ]
