# Generated by Django 4.1.7 on 2023-04-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
