# Generated by Django 4.1.7 on 2023-04-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_news_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('sub_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub Title')),
            ],
            options={
                'verbose_name_plural': 'News Banner',
            },
        ),
    ]
