# Generated by Django 4.1.7 on 2023-04-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteerdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='age',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
