# Generated by Django 4.1.7 on 2023-04-06 18:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremRawatAboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('sub_title', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/about/banner')),
            ],
            options={
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='PremRawattDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_section_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='First Section Description')),
                ('first_section_img', models.ImageField(null=True, upload_to='', verbose_name='First Section Image')),
                ('second_section_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Second Section Description')),
                ('second_section_img', models.ImageField(null=True, upload_to='', verbose_name='Second Section Image')),
                ('thired_section_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Third Section Description')),
                ('third_section_img', models.ImageField(null=True, upload_to='', verbose_name='Third Section Image')),
                ('fourth_section_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Third Section Description')),
                ('fourth_section_img', models.ImageField(null=True, upload_to='', verbose_name='Fourth Section Image')),
            ],
            options={
                'verbose_name_plural': 'Description',
            },
        ),
    ]
