# Generated by Django 4.1.7 on 2023-04-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
