# Generated by Django 4.1.7 on 2023-04-08 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetDonationAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, null=True)),
                ('isPaid', models.BooleanField(default=False, null=True)),
                ('order_date', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_methodology.setdonationamount')),
            ],
        ),
    ]
