# Generated by Django 4.1.7 on 2023-04-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methodology', '0002_donationmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='amount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
