# Generated by Django 4.1.7 on 2023-04-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methodology', '0003_alter_donationmodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='address',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='city',
            field=models.CharField(max_length=250, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='country',
            field=models.CharField(max_length=250, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='do_you_benifited',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='email',
            field=models.CharField(max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='first_name',
            field=models.CharField(max_length=250, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='last_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='phone_number',
            field=models.CharField(max_length=250, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='pin_code',
            field=models.CharField(max_length=250, null=True, verbose_name='Pin Code'),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='state',
            field=models.CharField(max_length=250, null=True, verbose_name='State'),
        ),
    ]
