# Generated by Django 4.1.7 on 2023-04-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methodology', '0004_donationmodel_address_donationmodel_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetDonationAmount',
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='pan',
            field=models.CharField(max_length=250, null=True, verbose_name='PAN'),
        ),
    ]
