# Generated by Django 4.1.7 on 2023-04-09 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_methodology', '0005_delete_setdonationamount_donationmodel_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Donation', to=settings.AUTH_USER_MODEL),
        ),
    ]
