# Generated by Django 4.1.7 on 2023-04-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methodology', '0006_alter_donationmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
