# Generated by Django 4.1.7 on 2023-04-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='home/banner')),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=350, null=True)),
                ('img', models.ImageField(null=True, upload_to='home/initiative')),
            ],
        ),
        migrations.CreateModel(
            name='LatestVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=350, null=True, verbose_name='Youtube Video Link')),
            ],
            options={
                'verbose_name_plural': 'Latest Videos',
            },
        ),
    ]
