# Generated by Django 4.1.7 on 2023-04-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_latestvideo_thumbnail_alter_latestvideo_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestvideo',
            old_name='link',
            new_name='play_list_link',
        ),
        migrations.AddField(
            model_name='latestvideo',
            name='video_link',
            field=models.CharField(max_length=350, null=True, verbose_name='Video Link'),
        ),
    ]
