# Generated by Django 4.1.7 on 2023-04-09 13:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_link_latestvideo_play_list_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
