# Generated by Django 4.1.7 on 2023-04-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initiative_details_alter_initiative_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='details',
        ),
    ]
