# Generated by Django 4.1.7 on 2023-04-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newsshelter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Initiative',
        ),
    ]
