# Generated by Django 4.1.7 on 2023-04-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_quicklinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutdescription',
            options={'verbose_name_plural': 'About Description'},
        ),
    ]
