# Generated by Django 4.1.7 on 2023-04-06 16:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutdescription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutdescription',
            options={'verbose_name_plural': 'Description'},
        ),
        migrations.AlterModelOptions(
            name='quicklinks',
            options={'verbose_name_plural': 'About Banners'},
        ),
        migrations.RemoveField(
            model_name='aboutdescription',
            name='description',
        ),
        migrations.AddField(
            model_name='aboutdescription',
            name='first_section_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='First Section Description'),
        ),
        migrations.AddField(
            model_name='aboutdescription',
            name='second_section_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Second Section Description'),
        ),
        migrations.AddField(
            model_name='aboutdescription',
            name='thired_section_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Third Section Description'),
        ),
    ]
