# Generated by Django 4.1.7 on 2023-04-06 16:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_aboutdescription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RvkAboutDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_section_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='First Section Description')),
                ('first_section_img', models.ImageField(null=True, upload_to='', verbose_name='First Section Image')),
                ('second_section_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Second Section Description')),
                ('second_section_img', models.ImageField(null=True, upload_to='', verbose_name='Second Section Image')),
                ('thired_section_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Third Section Description')),
                ('third_section_img', models.ImageField(null=True, upload_to='', verbose_name='Third Section Image')),
            ],
            options={
                'verbose_name_plural': 'Description',
            },
        ),
        migrations.RenameModel(
            old_name='AboutBanner',
            new_name='RvkAboutBanner',
        ),
        migrations.DeleteModel(
            name='AboutDescription',
        ),
        migrations.AlterModelOptions(
            name='quicklinks',
            options={'verbose_name_plural': 'Quick Banners'},
        ),
    ]
