# Generated by Django 4.1.7 on 2023-04-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rvkaboutdescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rvkaboutdescription',
            name='third_section_img',
        ),
    ]
