# Generated by Django 4.1.7 on 2023-04-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_rvkaboutdescription_third_section_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicklinks',
            options={'verbose_name_plural': 'Quick Links'},
        ),
        migrations.AlterModelOptions(
            name='rvkaboutbanner',
            options={'verbose_name_plural': 'Banners'},
        ),
    ]
