# Generated by Django 4.1.7 on 2023-04-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_quicklinks_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvkaboutdescription',
            name='first_section_description',
            field=models.TextField(blank=True, null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='rvkaboutdescription',
            name='second_section_description',
            field=models.TextField(blank=True, null=True, verbose_name='Second Section Description'),
        ),
        migrations.AlterField(
            model_name='rvkaboutdescription',
            name='thired_section_description',
            field=models.TextField(blank=True, null=True, verbose_name='Third Section Description'),
        ),
    ]
