# Generated by Django 4.1.7 on 2023-04-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_rvkaboutdescription_first_section_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklinks',
            name='link',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
